name: Account Service CI

on:
  push:
    branches: ["projects"]
    paths:
      - 'account-service/**'
      - '.github/workflows/account-service-ci.yml'
  pull_request:
    branches: ["projects"]
    paths:
      - 'account-service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./account-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B verify
      - name: Run Tests
        run: mvn test